import type { Store } from "../store/store.js";
import type { Evidence, Hypothesis, Ledger } from "../domain/types.js";

/**
 * Build a read-only, shareable ledger (for investors / accelerators). Pure
 * function of state so it is testable. Surfaces the gate state, every
 * assumption's status with its verified-evidence count, verdicts, and — crucially
 * — any gate overrides, so a reviewer can see if the founder bypassed the gate.
 */
export function buildExport(
  ledger: Ledger,
  hypotheses: Hypothesis[],
  verifiedCounts: Record<string, number>,
): string {
  const L: string[] = [];
  L.push("# ProofLedger — verified evidence report", "");
  L.push(`Gate: ${ledger.gate.state === "open" ? "OPEN" : "LOCKED"} — ${ledger.gate.reason}`, "");

  if (ledger.gate.overrides.length > 0) {
    L.push(`> ⚠ Build gate was overridden ${ledger.gate.overrides.length} time(s):`);
    for (const o of ledger.gate.overrides) L.push(`> - ${o.at} by ${o.by}: ${o.reason}`);
    L.push("");
  }

  for (const h of hypotheses) {
    const v = ledger.verdicts[h.id]?.verdict ?? "PENDING";
    L.push(`## ${h.claim}`);
    L.push(`Status: ${h.status} · Verdict: **${v}**`, "");
    L.push("| Assumption | Gate | Status | Verified evidence |");
    L.push("|---|---|---|---|");
    for (const a of h.assumptions) {
      L.push(`| ${a.text} | ${a.gate ? "◆" : ""} | ${a.status.toUpperCase()} | ${verifiedCounts[a.id] ?? 0} |`);
    }
    L.push("");
  }

  L.push("---", "_Generated by ProofLedger. Statuses derive only from machine-verified evidence._");
  return L.join("\n");
}

/** Count verified (any-tier) evidence rows per assumption across all hypotheses. */
export function verifiedCounts(store: Store, hypotheses: Hypothesis[]): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const h of hypotheses) {
    for (const a of h.assumptions) {
      counts[a.id] = store.listEvidenceFor(a.id).filter((e: Evidence) => e.status === "verified").length;
    }
  }
  return counts;
}
